name: Dockerize and Push

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: dockerregistry.wondy.no
                  username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: dockerregistry.wondy.no/ftbdirewolf:latest
